Henriquemvds/app-cars-sale

src/assets/pages/Home.jsx
src/assets/pages/VacancyDetails.jsx
src/main.jsx

criação de rtoas para detalhes das vagas concluída.

feat: creation of rtoas for vacancy details

---

package-lock.json
package.json
src/assets/pages/Home.css
src/assets/pages/Home.jsx

vinculação da api-cars-sale concluída.

feat: api-cars-sale linking

---

src/assets/pages/Home.jsx
src/assets/pages/VacancyDetails.jsx
src/main.jsx

adição de informações dos detalhes dos carros concluída.

feat: adding car details information

---

src/main.jsx

rotas dos detalhes do vagas melhorada.

fix: vacancy details routes

---

src/assets/pages/CategoriesDetails.jsx
src/assets/pages/Home.jsx
src/main.jsx

mudança de listagem da home para categorias de carros concluída.

refactor: change of home listing to car categories

---

index.html
src/assets/pages/Home.css
src/assets/pages/Home.jsx
src/index.css

adição da estilização da lista de categorias e sua responsividade concluída.

feat: adding category list styling and responsiveness

---

src/assets/pages/Home.jsx
src/index.css

feat: creation of main

---

src/assets/pages/Buy.jsx
src/main.jsx

adição de rota de compras concluída.

feat: purchase route

---

src/assets/pages/Buy.jsx
src/main.jsx

adição de rodapé na tela de compra concluída.

feat: adding footer to purchase screen

---

src/assets/components/OptionsHeader.jsx
src/assets/pages/Buy.jsx
src/assets/styles/Buy.css
src/assets/styles/OptionsHeader.css

adição de header na tela de compra concluída.

feat: adding header to purchase screen

---

src/assets/components/BuyItems.jsx
src/assets/pages/Buy.jsx
src/assets/styles/BuyItems.css
src/assets/styles/VehicleList.css

adição de item selecionado na tela de compra concluída.

feat: adding selected item to purchase screen

---

src/assets/components/BuyItem.jsx
src/assets/components/DetailsItem.jsx
src/assets/pages/Buy.jsx
src/assets/styles/Buy.css
src/assets/styles/BuyItem.css
src/assets/styles/DetailsItem.css
src/assets/styles/Footer.css

Adição das informações de venda do veículo concluída.

feat: Adding vehicle sales information

---

src/assets/pages/Sell.jsx
src/main.jsx

Adição de rota para venda de carro concluída.

feat: Addition of route for car sales

---

src/assets/pages/Sell.jsx
src/main.jsx

Adição de rodapé na tela de venda de carro concluída.

feat: Adding a footer to the car sales screen

---

src/assets/components/HeaderSell.jsx
src/assets/pages/Sell.jsx
src/assets/styles/HeaderSell.css
src/assets/styles/Sell.css

Adição de cabeçãlho na tela de venda de carro concluída.

feat: Adding a header to the car sales screen

---

src/assets/styles/components/Footer.css
src/assets/styles/components/TopicsNavs.css
src/assets/styles/components/VehicleList.css

adição de responsividade na Home concluída.

feat: adding responsiveness to the Home

---

src/assets/styles/components/VehicleList.css

melhoria de responsividade na Home concluída.

refactor: improving responsiveness at Home

---

src/assets/components/BuyItem.jsx
src/assets/styles/components/BuyItem.css
src/assets/styles/components/DetailsItem.css

adição de responsividade na tela de compra concluída.

feat: adding responsiveness to the purchase screen

---

src/index.css

bloqueio de scroll lateral concluído.

feat: side scroll lock

---

index.html
src/index.css

correção do bloqueio do scroll concluído.

fix: scroll lock fix

---

src/assets/styles/components/BuyItem.css
src/assets/styles/components/DetailsItem.css
src/assets/styles/components/Footer.css
src/index.css

projeto full screen concluído.

feat: full screen project

---

src/index.css

projeto full screen concluído.

fix: full screen project

---

src/assets/styles/components/FormSell.css

adição de responsividade na tela de venda de veículo concluída.

feat: adding responsiveness to the vehicle sales screen

---

src/assets/components/FormSell.jsx
src/assets/styles/components/FormSell.css

adição de responsividade na tela de venda de veículo melhorada.

fix: adding responsiveness to the vehicle sales screen

---

src/assets/components/VehicleList.jsx
src/assets/pages/Home.jsx

adição de listagem de carros pela api na home concluída.

feat: adding car listing via api to home

---

src/assets/components/BuyItem.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Home.jsx
src/main.jsx

listar carro selecionado na tela de compra concluído.

feat: list selected car on purchase screen

---

src/assets/components/VehicleList.jsx
src/assets/pages/Home.jsx

requisição da listagem de veículos melhorada.

refactor: vehicle listing request

---

src/assets/components/BuyItem.jsx
src/assets/components/DetailsItem.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Buy.jsx

adição de listagem do vendedor do carro
concluída.

feat: car seller listing addition

---

src/assets/components/VehicleList.jsx
src/assets/styles/components/VehicleList.css

problemas na renderização dos filtros resolvida.

fix: problems rendering filters

---

src/assets/components/VehicleList.jsx

melhoria na filtragem de carros concluída.

fix: car filtering improvement

---

src/assets/components/DetailsItem.jsx

adição de compra de carro concluído.

feat: car purchase addition

---

src/assets/components/DetailsItem.jsx
src/assets/components/VehicleList.jsx

adição de filtro de carro por preço concluído.

feat: adding car filter by price

---

src/assets/components/FormSell.jsx
src/assets/components/VehicleList.jsx

cadastro de vendedor concluído.

feat: seller registration

---

src/assets/components/FormSell.jsx

adição de cpf em vendedor concluída.

feat: adding CPF to seller

---

src/assets/components/FormSell.jsx

conexão de formulário ao banco de dados concluída.

feat: form connection to database

---

src/assets/components/Footer.jsx
src/assets/components/FormSell.jsx

adição de upload de imagem concluída.

feat: adding image upload

---

src/assets/components/DetailsItem.jsx
src/assets/components/FormSell.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Home.jsx

mudança de endereçamento de requisições concluída.

refactor: change of request addressing

---

src/assets/components/FormSell.jsx
src/assets/components/VehicleList.jsx

feat: enabling requests

---

src/assets/components/DetailsItem.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Buy.jsx
src/assets/pages/Home.jsx

fix: arranging requests

---

src/assets/components/DetailsItem.jsx
src/assets/components/FormSell.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Buy.jsx
src/assets/pages/Home.jsx

fix: authorization of requests

---

src/assets/components/FormSell.jsx
src/assets/components/VehicleList.jsx

mudança de requisição de imagem para o backend concluída.

fix: image request change to the backend

---

src/assets/components/BuyItem.jsx
src/assets/components/DetailsItem.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Buy.jsx
src/assets/pages/Home.jsx

mudança de rotas da api concluída.

feat: changing api routes

---

src/assets/components/BuyItem.jsx
src/assets/components/DetailsItem.jsx
src/assets/components/TopicsNavs.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Buy.jsx
src/main.jsx

adição de descrição na listagem de veículos concluída.

feat: adding description to vehicle listing

---

src/assets/styles/components/VehicleList.css

responsividade na listagem de veículos concluída.

feat: responsiveness in vehicle listing

---

src/assets/styles/components/BuyItem.css

responsividade nos detalhes de pagamento e do vendedor concluído.

fix: responsiveness in payment and seller details

---

src/assets/components/BuyItem.jsx
src/assets/components/InfoHeader.jsx
src/assets/components/TopicsNavs.jsx
src/assets/components/VehicleList.jsx
src/assets/pages/Home.jsx
src/assets/styles/components/VehicleList.css

melhoria nas formas de filtragem concluída.

fix: improvement in filtering methods

---

index.html
package-lock.json
package.json
src/assets/components/VehicleList.jsx
src/assets/pages/Home.jsx

melhoria nas formas de filtragem com paginação concluída.

fix: improvement in filtering forms with pagination

---

index.html
src/assets/components/VehicleList.jsx

otimização de filtros de veículos concluída.

fix: vehicle filter optimization

---

src/assets/components/VehicleList.jsx

adição de paginação responsiva concluída.

feat: adding responsive pagination

---

src/assets/components/BuyItem.jsx
src/assets/components/InfoHeader.jsx
src/assets/components/TopicsNavs.jsx
src/assets/components/VehicleList.jsx
src/assets/context/vehicles.jsx
src/assets/pages/Buy.jsx
src/assets/pages/Home.jsx
src/main.jsx

adição de contexto dos dados da api concluída.

feat: adding context of api data

---

src/assets/components/TopicsNavs.jsx
src/assets/components/VehicleList.jsx
src/assets/context/vehicles.jsx

adição de filtro de veículos por categorias concluído.

feat: adding vehicle filter by categories

---

src/assets/components/VehicleList.jsx

resolução de problemas de filtro de veículos concluído.

fix: vehicle filter troubleshooting

---

src/assets/components/BuyItem.jsx
src/assets/components/VehicleList.jsx

adição de alerta de compra concluído.

feat: adding purchase alert
